# Description: Brewfile for my macOS setup
# Usage: brew bundle --file=Brewfile

tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "zstd"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "ccls"
brew "cmake"
brew "difftastic"
brew "gcc"
brew "libavif"
brew "gd"
brew "gdk-pixbuf"
brew "unbound"
brew "gnutls"
brew "go"
brew "gopls"
brew "netpbm"
brew "gts"
brew "librsvg"
brew "graphviz"
brew "guile"
brew "node"
brew "nvm"
brew "platformio"
brew "python@3.11"
brew "python-tk@3.11"
brew "rbenv"
brew "ripgrep"
brew "pngpaste"
brew "d12frosted/emacs-plus/emacs-plus@29", args: ["with-native-comp"]
cask "amethyst"
cask "font-devicons"
cask "font-hack-nerd-font"
cask "font-inconsolata-nerd-font"
